version: '3.5'

services:
  ticketapp-demo:
    build:
      context: .
      dockerfile: TicketAppDemo.Dockerfile
    container_name: ticketapp-demo
    ports:
      - '10443:80'
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDemo
