version: '3.5'

networks:
  app-net:
    driver: bridge

services:
  ticketapp-demo:
    build:
      context: .
      dockerfile: TicketAppDemo.Dockerfile
    container_name: ticketapp-demo
    ports:
      - '5555:80'
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDemo
    networks:
      - ticketapp-net
